print("++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++")
print("+                                                ------                                                          +")
print("+                    XXXXXXXXXXXXXXXXXXXXXXXX   | HELP |   XXXXXXXXXXXXXXXXXXXXXXXXXX                            +")
print("+                                                ------                                                          +")
print("++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++")
print("+                                                                                                                +")
print("+  version: 1.0.0                                                                                                +")
print("+  name: Roots of equations                                                                                      +")
print("+                                                                                                                +")
print("++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++")
print("+                                                                                                                +")
print("+      This program is made by  PARTH R. BARAIYA.                                                                +")
print("+      For any Quaries Please Contact: +919427212719                                                             +")
print("+      E-Mail:  170303105019@paruluniversity.ac.in                                                               +")
print("+                                                                                                                +")
print("++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++")
print("+                                                                                                                +")
print("+                 XXXXXXXXXXXXXXXXXXXXXXXXXXX   THE END   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                    +")
print("+                                                                                                                +")
print("++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++")
