import math
print("+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++")
print("+                                                                                                                                     +")
print("+                                                                                                                                     +")
print("------------------------------------------This program is to find roots of equation.---------------------------------------------------")
print("+                                                                                                                                     +")
print("+                                                                                                                                     +")
print("+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++")
print("+   Rules to enter the equation:                                                                                                      +")
print("+         1. Equation must contain only one constant.                                                                                 +")
print("+                                                                                                                                     +")
print("+         2. Constant must be capital i.e. X,Y,Z,etc.                                                                                 +")
print("+                                                                                                                                     +")
print("+         3. To enter any transcedential or logarithemic function follow given pattern:                                               +")
print("+             Logarithemic Function:                                                                                                  +")
print("+                1. log                                                                                                               +")
print("+                     syntax: log(content,base)                                                                                       +")
print("+                     description: content and base can be any constant or sub equation                                               +")
print("+                                  eg: X^2,3,10,e,etc.                                                                                +")
print("+                                  content and base can not be or evaluate to zero.                                                   +")
print("+                2. sin,cos,tan,cot,cosec,cot,sec                                                                                     +")
print("+                     syntax: sin(content)                                                                                            +")
print("+                             cos(content)                                                                                            +")
print("+                             tan(content)                                                                                            +")
print("+                             cot(content)                                                                                            +")
print("+                             cosec(content)                                                                                          +")
print("+                             cot(content)                                                                                            +")
print("+                             sec(content)                                                                                            +")
print("+                     description: content can be any constant or sub equation and function name must be in small latters             +")
print("+                                  this program will take content as radian values this will not work for degree.                     +")
print("+                                                                                                                                     +")
print("+         4. This program supports 'pi' and 'e' constant                                                                              +")
print("+               syntax for 'pi' is 'pi' and for 'e' is 'e'(In small latters)                                                          +")
print("+               value for pi will evaluate to ",math.pi,"                                                                     +")
print("+               value for e will evaluate to ",math.e,"                                                                      +")
print("+                                                                                                                                     +")
print("+         5. After entering equation you have to enter the efficiency of root                                                         +")
print("+                                                                                                                                     +")
print("+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++")
print("+                                                                                                                                     +")
print("+      Note:    All the answer given by this program are approximate.                                                                 +")
print("+                                                                                                                                     +")
print("+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++")
